version: '3.3'

services:
   db:
     image: mariadb:10.3
     restart: always
     environment:
       MARIADB_ROOT_PASSWORD: some-mariadb
       MARIADB_DATABASE: mariadb
       MARIADB_USER: domenic
       MARIADB_PASSWORD: domenic

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin:latest
     links:
       - db
     ports:
       - "8000:80"
     restart: always
     environment:
       PMA_HOST: db
       PMA_PORT: 3306
       PMA_USER: domenic
       PMA_PASSWORD: domenic
       PMA_ARBITRARY: 1
volumes:
    db_data: {}